<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Games.aspx.cs" Inherits="Games" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
&nbsp;<asp:SqlDataSource ID="ViewGames" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:databaseConnectionString %>" DeleteCommand="DELETE FROM [Games] WHERE [Game_ID] = ? AND (([Game_Code] = ?) OR ([Game_Code] IS NULL AND ? IS NULL)) AND (([Game_Name] = ?) OR ([Game_Name] IS NULL AND ? IS NULL)) AND (([Game_DurationInHours] = ?) OR ([Game_DurationInHours] IS NULL AND ? IS NULL)) AND (([Game_Description] = ?) OR ([Game_Description] IS NULL AND ? IS NULL)) AND (([Field1] = ?) OR ([Field1] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [Games] ([Game_ID], [Game_Code], [Game_Name], [Game_DurationInHours], [Game_Description], [Field1]) VALUES (?, ?, ?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="<%$ ConnectionStrings:databaseConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Games]" UpdateCommand="UPDATE [Games] SET [Game_Code] = ?, [Game_Name] = ?, [Game_DurationInHours] = ?, [Game_Description] = ?, [Field1] = ? WHERE [Game_ID] = ? AND (([Game_Code] = ?) OR ([Game_Code] IS NULL AND ? IS NULL)) AND (([Game_Name] = ?) OR ([Game_Name] IS NULL AND ? IS NULL)) AND (([Game_DurationInHours] = ?) OR ([Game_DurationInHours] IS NULL AND ? IS NULL)) AND (([Game_Description] = ?) OR ([Game_Description] IS NULL AND ? IS NULL)) AND (([Field1] = ?) OR ([Field1] IS NULL AND ? IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_Game_ID" Type="Int32" />
                <asp:Parameter Name="original_Game_Code" Type="String" />
                <asp:Parameter Name="original_Game_Code" Type="String" />
                <asp:Parameter Name="original_Game_Name" Type="String" />
                <asp:Parameter Name="original_Game_Name" Type="String" />
                <asp:Parameter Name="original_Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="original_Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="original_Game_Description" Type="String" />
                <asp:Parameter Name="original_Game_Description" Type="String" />
                <asp:Parameter Name="original_Field1" Type="String" />
                <asp:Parameter Name="original_Field1" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Game_ID" Type="Int32" />
                <asp:Parameter Name="Game_Code" Type="String" />
                <asp:Parameter Name="Game_Name" Type="String" />
                <asp:Parameter Name="Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="Game_Description" Type="String" />
                <asp:Parameter Name="Field1" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Game_Code" Type="String" />
                <asp:Parameter Name="Game_Name" Type="String" />
                <asp:Parameter Name="Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="Game_Description" Type="String" />
                <asp:Parameter Name="Field1" Type="String" />
                <asp:Parameter Name="original_Game_ID" Type="Int32" />
                <asp:Parameter Name="original_Game_Code" Type="String" />
                <asp:Parameter Name="original_Game_Code" Type="String" />
                <asp:Parameter Name="original_Game_Name" Type="String" />
                <asp:Parameter Name="original_Game_Name" Type="String" />
                <asp:Parameter Name="original_Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="original_Game_DurationInHours" Type="Int32" />
                <asp:Parameter Name="original_Game_Description" Type="String" />
                <asp:Parameter Name="original_Game_Description" Type="String" />
                <asp:Parameter Name="original_Field1" Type="String" />
                <asp:Parameter Name="original_Field1" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <a href="AddGames.aspx">Add Games</a></p>
        <h1>View Games</h1></p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Game_ID" DataSourceID="ViewGames">
            <Columns>
                <asp:BoundField DataField="Game_ID" HeaderText="Game ID" InsertVisible="False" ReadOnly="True" SortExpression="Game_ID" />
                <asp:BoundField DataField="Game_Code" HeaderText="Game Code" SortExpression="Game_Code" />
                <asp:BoundField DataField="Game_Name" HeaderText="Game Name" SortExpression="Game_Name" />
                <asp:BoundField DataField="Game_DurationInHours" HeaderText="Game DurationInHours" SortExpression="Game_DurationInHours" />
                <asp:BoundField DataField="Game_Description" HeaderText="Game Description" SortExpression="Game_Description" />
                <asp:BoundField DataField="Field1" HeaderText="Game Photo" SortExpression="Field1" />
            </Columns>
        </asp:GridView>
    </p>
</asp:Content>

